name: Copy All Files via GitHub Runner

on:
  workflow_dispatch:

jobs:
  copy-ec2:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Setup SSH Key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_A_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_B_IP }} >> ~/.ssh/known_hosts

      # Step 2: Debug SSH Key (check format)
      - name: Debug SSH Key
        run: |
          head -5 ~/.ssh/id_rsa
          file ~/.ssh/id_rsa || true

      # Step 3: Test SSH to EC2 A
      - name: Test SSH to EC2 A
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_A_IP }} "echo 'SSH to EC2 A works'"

      # Step 4: Copy all files from EC2 A → GitHub runner
      - name: Pull files from EC2 A
        run: |
          mkdir -p ./ec2-files
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ubuntu@${{ secrets.EC2_A_IP }}:/home/ubuntu/* ./ec2-files/

      # Step 5: Push files from GitHub runner → EC2 B
      - name: Push files to EC2 B
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./ec2-files/* ubuntu@${{ secrets.EC2_B_IP }}:/home/ubuntu/
