name: Copy All Files via GitHub Runner
on:  workflow_dispatch
jobs:
   copy-ec2:    
   runs-on: ubuntu-latest   
   steps:       
    - name: Setup SSH Key        
      run: |
        mkdir -p ~/.ssh   
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa         
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_A_IP }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.EC2_B_IP }} >> ~/.ssh/known_hosts
        run: |
         ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_A_IP }} "echo 'SSH to EC2 A works'"

    - name: Pull all files from EC2 A
      run: |
        mkdir -p ./ec2-files
        scp -r -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_A_IP }}:/home/ubuntu/* ./ec2-files/


name: Push all files to EC2 B
     run: |
       scp -r -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./ec2-files/* ubuntu@${{ secrets.EC2_B_IP }}:/home/ubuntu/
