name: Debug IAM User Status

on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS
      run: |
        aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws configure set region ap-south-1

    - name: Test with different regions
      run: |
        echo "Testing with ap-south-1:"
        AWS_DEFAULT_REGION=ap-south-1 aws sts get-caller-identity || echo "Failed with ap-south-1"
        
        echo "Testing with us-east-1:"
        AWS_DEFAULT_REGION=us-east-1 aws sts get-caller-identity || echo "Failed with us-east-1"
