name: Manage EC2 Instance

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'start'
        type: choice
        options:
        - start
        - stop

jobs:
  manage-ec2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws configure set region ap-south-1
        aws configure set output json

    - name: Verify AWS Connection
      run: |
        echo "Testing AWS credentials..."
        aws sts get-caller-identity
        echo "✅ AWS credentials are valid!"

    - name: Start EC2 Instance
      if: github.event.inputs.action == 'start'
      run: |
        echo "Starting EC2 instance: i-0418f0fdd1b4ed30f"
        aws ec2 start-instances --instance-ids i-0418f0fdd1b4ed30f
        echo "Waiting for instance to be running..."
        aws ec2 wait instance-running --instance-ids i-0418f0fdd1b4ed30f
        echo "✅ Instance is now running!"

    - name: Stop EC2 Instance
      if: github.event.inputs.action == 'stop'
      run: |
        echo "Stopping EC2 instance: i-0418f0fdd1b4ed30f"
        aws ec2 stop-instances --instance-ids i-0418f0fdd1b4ed30f
        echo "Waiting for instance to be stopped..."
        aws ec2 wait instance-stopped --instance-ids i-0418f0fdd1b4ed30f
        echo "✅ Instance is now stopped!"

    - name: Get Instance Status
      run: |
        echo "📊 Current Instance Status:"
        aws ec2 describe-instances --instance-ids i-0418f0fdd1b4ed30f \
          --query 'Reservations[*].Instances[*].[InstanceId,State.Name,InstanceType,PublicIpAddress,PrivateIpAddress]' \
          --output table
