name: Manage EC2 Instance

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'start'
        type: choice
        options:
        - start
        - stop

jobs:
  manage-ec2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS CLI properly
      run: |
        # Create AWS configuration directory
        mkdir -p ~/.aws
        
        # Create config file
        cat << EOF > ~/.aws/config
[default]
region = ap-south-1
output = json
EOF

        # Create credentials file
        cat << EOF > ~/.aws/credentials
[default]
aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
EOF

        # Verify the files were created
        echo "AWS config file:"
        cat ~/.aws/config
        echo "AWS credentials file (first few chars of key):"
        head -c 20 ~/.aws/credentials && echo "..."

    - name: Test AWS connection
      run: |
        aws sts get-caller-identity

    - name: Execute EC2 Action
      run: |
        if [ "${{ github.event.inputs.action }}" == "start" ]; then
          echo "Starting EC2 instance: i-0418f0fdd1b4ed30f"
          aws ec2 start-instances --instance-ids i-0418f0fdd1b4ed30f
          echo "Waiting for instance to be running..."
          aws ec2 wait instance-running --instance-ids i-0418f0fdd1b4ed30f
          echo "Instance is now running!"
        elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
          echo "Stopping EC2 instance: i-0418f0fdd1b4ed30f"
          aws ec2 stop-instances --instance-ids i-0418f0fdd1b4ed30f
          echo "Waiting for instance to be stopped..."
          aws ec2 wait instance-stopped --instance-ids i-0418f0fdd1b4ed30f
          echo "Instance is now stopped!"
        fi

    - name: Get Instance Details
      run: |
        echo "Instance Details:"
        aws ec2 describe-instances --instance-ids i-0418f0fdd1b4ed30f \
          --query 'Reservations[*].Instances[*].[InstanceId,State.Name,InstanceType,PublicIpAddress,PrivateIpAddress,Tags[?Key==`Name`].Value|[0]]' \
          --output table
