name: EC2 Start/Stop

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose whether to start or stop the EC2 instance"
        required: true
        default: "start"
        type: choice
        options:
          - start
          - stop

jobs:
  manage-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Start or Stop EC2 Instance
        run: |
          INSTANCE_ID="i-0418f0fdd1b4ed30f"   
          if [ "${{ github.event.inputs.action }}" = "start" ]; then
            echo "Starting EC2 instance $INSTANCE_ID ..."
            aws ec2 start-instances --instance-ids $INSTANCE_ID
          else
            echo "Stopping EC2 instance $INSTANCE_ID ..."
            aws ec2 stop-instances --instance-ids $INSTANCE_ID
          fi
